### ISSUE TITLE
Bug/Warning: Perpetuum.RequestHandlers/Chat.cs - Hash calculated improperly

### ISSUE THREAD

**Issue by nref-dan** [OpenPerpetuum/OP-Project#123]
Line 62: `var hash = (ulong) x << 32 | (ulong) y;` this could cause incorrect "OR'ing" with negative integers and causes an unnecessary compiler warning.

This is a "should never happen" scenario, however it's important to understand the mechanism and use it correctly. If not, the wrong pattern may be used in future.

**Solution:** Rather than casting straight to ulong, cast to uint first (the variables are passed in as int anyway). This will prevent sign extension (also known as sign fill). 
```
int x = -1; // 0xFFFF
ulong y = 0x0123456700000000;
ulong xlong = (ulong)x; // xlong = 0xFFFFFFFFFFFFFFFF due to sign extension
ulong output =y | xlong;

// output: 0xFFFFFFFFFFFFFFFF, desired: 0x012345670000FFFF
```

**Comment by MikeJeffers** [comment]
closed by https://github.com/OpenPerpetuum/PerpetuumServer/pull/103
