### ISSUE TITLE
NPC - EP Reward issue

### ISSUE THREAD

**Issue by MikeJeffers** [OpenPerpetuum/OP-Project#133]
Players are being removed from the threatmanager, but are still aggressing and killing the npc.
Thus they are not on the threatmanager on-death when EP is rewarded.

Fix/Impl detail: Collect and manage separate table for NPC to track aggressors, only remove with simple time-expiration.
(Note: timeout should be much greater than reload+cycle times)

**Comment by pbezzeg** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [NPC - EP Reward issue](https://trello.com/c/eEHPUtln/10-npc-ep-reward-issue)

**Comment by MikeJeffers** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [NPC threatmanager bug](https://trello.com/c/G9h8SpSG/4-npc-threatmanager-bug)
