### ISSUE TITLE
New Player Welcoming Features: Mail on Arrive/Depart Tutorial

### ISSUE THREAD

**Issue by MikeJeffers** [OpenPerpetuum/OP-Project#143]
We need the ability to send a template mail/message to a new player when they either arrive, or exit the tutorial (or both).
This mail should be easily customized - avoid putting in source.  DB? Disk? up to you!
Mail text will need to support hyperlinks.

**Comment by clouths** [comment]
I've tested hyperlinks for mail and I could not figure what is the text format to support them, maybe the game does not support hyperlinks on mails but at least hyperlinks are supported on the chat.
