### ISSUE TITLE
Ore field keep-out radius

### ISSUE THREAD

**Issue by MikeJeffers** [OpenPerpetuum/OP-Project#145]
Set minimum distances from Terminals and Teleports for mineral nodes to spawn (by ore type?)
Request: 750/750 for Terminal and teleports for epriton

**Comment by clouths** [comment]
Does the minimum distance also applies to the field terminals?

**Comment by MikeJeffers** [comment]
Good question - no, I believe its the issue of safety related to DockingBases.
