### ISSUE TITLE
Add support for localization

### ISSUE THREAD

**Issue by clouths** [OpenPerpetuum/OP-Project#150]
A recent announcement for the official PerpetuumServer added support for localisation.
* [Link to announcement](https://twitter.com/perpetuumonline/status/1124635290788859904)
* [Technical information](https://twitter.com/perpetuumonline/status/1124636463352750080)
* [Additional technical information](https://twitter.com/perpetuumonline/status/1124636634430021632)

PerpetuumOnline/PerpetuumServer related commits:
* [Custom dictionaries](https://github.com/PerpetuumOnline/PerpetuumServer/commit/aede0b1526a1715ad8605265a9267fce5797f68c)
* [Add language list as a comment](https://github.com/PerpetuumOnline/PerpetuumServer/commit/4a0c52511452d34754f3f71712905dd36a668e73)

The goal of this task is to implement the localisation in a way we can easily update information where the localisation information will be stored in the database.
Note: The goal is, at least for this issue, is to add the support for localization. Other issues can/will be created for the content of the localization.

**Comment by MikeJeffers** [comment]
Closed by https://github.com/OpenPerpetuum/PerpetuumServer/pull/102
