### ISSUE TITLE
EP curve and target

### ISSUE THREAD

**Issue by MikeJeffers** [OpenPerpetuum/OP-Project#151]
Complaints about 500k EP being too short, people hitting it too quickly, players feeling like they are suddenly "stopped" from earning EP.

Extend target out, lower power of curve, ensure area under curve is greater than previous so that total boosted period is increased.

Round 2 on https://github.com/OpenPerpetuum/OP-Project/issues/45

**Comment by clouths** [comment]
Is there a way to test this curve?
I understand the exponent and the desired EP target where (I think) when the EP target is achieved, the boost stops working.

**Comment by MikeJeffers** [comment]
Use the OPDB tool or manipulate your accounts EP directly in the DB, verify the ep multiplier as computed and displayed in Agent Profile > Extensions > EP rewards
Note: the client caches the EP multiplier, open and close and re-open the agent profile window to see the most current multiplier.
