### ISSUE TITLE
Research: Falloff - How is calculated/how to change

### ISSUE THREAD

**Issue by MikeJeffers** [OpenPerpetuum/OP-Project#16]
Balance team request: Falloff is convoluted curve, 
A) what is it exactly?
B) can we customize?
C) set floor? (end at x% of damage, instead of 0%)

**Comment by Sellafield** [comment]
assuming we have Opt as optimal range, Fall as falloff, O-F as total range, and Dist - as actual diatance to target, we can calculate damage modifier Mod as multiplier using these rules:

if Dist < Opt then Mod = 1;
if Dist > O-F then Mod = 0;
if Dist > Opt and < O-F then Mod = (Sin((Dist - Opt) / (O-F - Opt) * 3.14159265358979 + 1.5707963267949) + 1) / 2

unfirtunately there is no way to change that until we get the source code. after that, we can just switch formula to

Mod = (Sin((Dist - Opt) / (O-F - Opt) * 1.5707963267949 + 1.5707963267949) + 1) / 2

, which will limit the results between 1 and 0.5

keep in mind tho, that it's affect not only just damage calculation but also terraforming.

**Comment by Sellafield** [comment]
Upd: 

That's be MathHelper.cs line 46 (DistanceFalloff method)

here it takes 6 params which are:

double nearRadius - that'd be Opt
double farRadius - that'd be O-F
double originX, originY - your position coords
double targetX, targetY - target's position coords

Dist is calculated inside the method by hypotenuse formula, using both your and you target's coords to get the sides of the triangle.
