### ISSUE TITLE
Outpost stability - AFK decay

### ISSUE THREAD

**Issue by MikeJeffers** [OpenPerpetuum/OP-Project#161]
If the `owner` does not do a SAP (or other stability affecting event*) for X period of time, or for X occurrences of a SAP - decay the outpost stability by Y.

*not mvp, and might be too tricky to balance given other features

**Comment by pbezzeg** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Outpost stability - AFK decay](https://trello.com/c/oFrR0mQO/9-outpost-stability-afk-decay)

**Comment by MikeJeffers** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Outpost Stability Decay](https://trello.com/c/hIQtmSq0/3-outpost-stability-decay)

**Comment by MikeJeffers** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Outpost Stability Decay](https://trello.com/c/hIQtmSq0/3-outpost-stability-decay)
