### ISSUE TITLE
SAP loot rework

### ISSUE THREAD

**Issue by MikeJeffers** [OpenPerpetuum/OP-Project#162]
Content team DB work to re work loot tables with different items and reward model.

Research that loot behaves as expected if not a multiple of 5 (probably does, but all stability numbers have been 5)

**Comment by pbezzeg** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [SAP loot rework](https://trello.com/c/iEQN5sgl/8-sap-loot-rework)
