### ISSUE TITLE
Specimen SAP items (new)

### ISSUE THREAD

**Issue by MikeJeffers** [OpenPerpetuum/OP-Project#163]
Create new set of items, add production tables (dbo.components) and CT-items for their construction.

Seed the CT's via the syndicate shop

Rework the specimen requirements table to only be these items (and potentially other things, like tokens -- design team feedback needed)

**Comment by pbezzeg** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Specimen SAP items (new)](https://trello.com/c/IHWD0b4f/7-specimen-sap-items-new)
