### ISSUE TITLE
(Relics) Intrusion Relic

### ISSUE THREAD

**Issue by MikeJeffers** [OpenPerpetuum/OP-Project#164]
Each outpost will have X-maximum relics that can spawn in a random location between some min-max distance from the terminal.
Upon finding a relic, 1 stability point is to be added to the stability of the outpost IF:
 - Found by a member of the owner corp
 - *Found by an ally
If found by a neutral: 0 effect
If found by an enemy (negative relation on either side) -1

They should respawn at a rate of 1 per X hours

**Comment by pbezzeg** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(Relics) Intrusion Relic](https://trello.com/c/4q8lQQNh/6-relics-intrusion-relic)
