### ISSUE TITLE
Character can become stuck when deploying player owned structures

### ISSUE THREAD

**Issue by LoyalServant** [OpenPerpetuum/OP-Project#21]
If you are on the center of the tile that the structure is deployed on and build it without moving you can become stuck inside of the structure.
If you log out and back in while stuck inside of the structure the server will place you at 0,0 and you will be stuck there instead.

**Comment by MikeJeffers** [comment]
Confirmed behavior on official too.  (I deconstructed it to escape...)

**Comment by MikeJeffers** [comment]
Closed by: https://github.com/OpenPerpetuum/PerpetuumServer/pull/128
