### ISSUE TITLE
Training Scarab Spawns try to path out of pen

### ISSUE THREAD

**Issue by MikeJeffers** [OpenPerpetuum/OP-Project#41]
Scarabs spawn npcs path into the wall, which has them show outside of the walled pen.
Adjust lasso or spawn radius to keep them inside the pen, verify with client in tutorial.
Should be DB change.

**Comment by MikeJeffers** [comment]
What's status on this?  Ville had local fix.

**Comment by LoyalServant** [comment]
Is this a blocking / control layer problem or the XY of the pen?

**Comment by MikeJeffers** [comment]
No, it was the "home range" of the npc flock.  @Phantomburn fixed, and is on server now.
Closed!
