### ISSUE TITLE
Armour not repaired at field terminals when add/removing modules

### ISSUE THREAD

**Issue by LoyalServant** [OpenPerpetuum/OP-Project#71]
A cause for this has not been established.

**Comment by MikeJeffers** [comment]
Overrides any damage or repair achieved during equip window opening

**Comment by MikeJeffers** [comment]
Armor and Accumulator maintain their Ratio through the equipping process.
Taking damage, losing or gaining accumulator, or any other manipulations to the armor/accum state maintains its _ratio_ from the time before the equipment is transacted.

**Comment by MikeJeffers** [comment]
Closed by: https://github.com/OpenPerpetuum/PerpetuumServer/pull/36
