### ISSUE TITLE
Field Terminal Bug #3623 Geoscanner equip client runtime error crash

### ISSUE THREAD

**Issue by MikeJeffers** [OpenPerpetuum/OP-Project#73]
Geoscanner in particular presents major problems with re/equipping at field terminals.

Geoscanner window often fails to display results after equip at field terminal
Client will crash after some combination of actions using and equipping geoscanner at field terminal

Needs Eyes

**Comment by LoyalServant** [comment]
Video of the issue:
https://youtu.be/uFjbHhylcfw

**Comment by MikeJeffers** [comment]
This was fixed by AC
