### ISSUE TITLE
NPC Plasma loot bug

### ISSUE THREAD

**Issue by MikeJeffers** [OpenPerpetuum/OP-Project#76]
Likely a DB entry issue:
Plasma fields for existing npc bots read: probability=1, repackaged=0, dontdamage=0
Problematic definitions read: probability=1, repackaged=0, dontdamage=1

"Damage" on a stacked quantity of items seems to produce the relative % between minquantity and quantity that show up in the lootcontainer.

Easy fix -  change field
Better fix?

**Comment by MikeJeffers** [comment]
Quick script to test:
```
UPDATE npcloot
SET dontdamage=0
WHERE lootdefinition in (SELECT definition FROM entitydefaults WHERE entitydefaults.definitionname like '%_reactor_plasma%');
```

**Comment by MikeJeffers** [comment]
Dont forget kernals too!

**Comment by LoyalServant** [comment]
This isn't a db problem but the manner in which the server initializes the loot tables.

**Comment by MikeJeffers** [comment]
Closed by: https://github.com/OpenPerpetuum/PerpetuumServer/pull/44
